"""
CREATE QUERIES
"""

ADDRESSES_TABLE: str = 'addresses'
CITIES_TABLE: str = 'cities'
RESIDENCE_TABLE: str = 'residences'
MODE_TABLE: str = 'modes'
PORT_TABLE: str = 'ports'
VISA_TABLE: str = 'visas'


CREATE_ADDRESSES: str = f"""
CREATE TABLE {ADDRESSES_TABLE} IF NOT EXISTS(
    uid VARCHAR(2) NOT NULL PRIMARY KEY,
    address VARCHAR(256) NOT NULL
);
"""

CREATE_CITIES: str = f"""
CREATE TABLE {CITIES_TABLE} IF NOT EXISTS(
    uid INT NOT NULL PRIMARY KEY,
    city VARCHAR(256) NOT NULL
);
"""

CREATE_RESIDENCE: str = f"""
CREATE TABLE {RESIDENCE_TABLE} IF NOT EXISTS(
    uid INT NOT NULL PRIMARY KEY,
    residence VARCHAR(256) NOT NULL
);
"""

CREATE_MODE: str = f"""
CREATE TABLE {MODE_TABLE} IF NOT EXISTS(
    uid INT NOT NULL PRIMARY KEY,
    mode VARCHAR(256) NOT NULL
);
"""

CREATE_PORT: str = f"""
CREATE TABLE {PORT_TABLE} IF NOT EXISTS(
    uid INT NOT NULL PRIMARY KEY,
    mode VARCHAR(256) NOT NULL
);
"""

CREATE_VISA: str = f"""
CREATE TABLE {VISA_TABLE} IF NOT EXISTS(
    uid INT NOT NULL PRIMARY KEY,
    visa VARCHAR(256) NOT NULL
);
"""
